
-- Migration: 05_create_macro_indicators
-- Purpose: Store historical and daily macro data (GDP, CPI, Forex)

CREATE TABLE IF NOT EXISTS macro_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_key TEXT NOT NULL, -- Examples: 'VN_GDP_YOY', 'USDVND_OFFICIAL', 'USDVND_BLACK_MARKET'
    date DATE NOT NULL,
    value NUMERIC,
    source TEXT, -- 'FMP', 'MANUAL', 'GSO'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Optimization: Index for fast lookups by key and date
CREATE UNIQUE INDEX IF NOT EXISTS idx_macro_key_date ON macro_indicators(indicator_key, date);

-- Optional: Enable RLS (Row Level Security) if needed later
ALTER TABLE macro_indicators ENABLE ROW LEVEL SECURITY;

-- Policy: Public read access
CREATE POLICY "Public indicators are viewable by everyone" 
ON macro_indicators FOR SELECT USING (true);

-- Policy: Service role (backend) update access
CREATE POLICY "Service role can insert/update indicators" 
ON macro_indicators FOR ALL USING (true) WITH CHECK (true);
