-- Create table for storing economic events
CREATE TABLE IF NOT EXISTS economic_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name TEXT NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    currency VARCHAR(3) NOT NULL,
    
    -- Data columns (Stored as TEXT to handle special formats or units, e.g., '5.2%', '200K')
    previous TEXT,
    forecast TEXT,
    actual TEXT,
    
    -- Impact assessment
    impact_level TEXT CHECK (impact_level IN ('High', 'Medium', 'Low')),
    
    -- AI and Local Analysis
    ai_commentary TEXT,       -- Generated by Gemini
    ai_sentiment TEXT CHECK (ai_sentiment IN ('BULLISH', 'BEARISH', 'NEUTRAL')), 
    vn_impact TEXT,           -- Specific impact on Vietnam market (VNI, USD/VND)
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for querying by time is crucial for a calendar
CREATE INDEX IF NOT EXISTS idx_economic_events_time ON economic_events(event_time);

-- Index for filtering by high impact
CREATE INDEX IF NOT EXISTS idx_economic_events_impact ON economic_events(impact_level);
