-- Create table for Macro Indicators (Hybrid: Scraped & Manual)
CREATE TABLE IF NOT EXISTS macro_indicators (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    indicator_key TEXT NOT NULL, -- e.g. 'USDVND_BLACK_MARKET', 'VN_GDP_YOY', 'OWL_COMMENTARY_FISCAL'
    date DATE NOT NULL,
    value NUMERIC, -- Numeric value (e.g. 25400, 6.5)
    text_content TEXT, -- For Owl Commentary or non-numeric status
    source TEXT DEFAULT 'MANUAL', -- 'MANUAL', 'SCRAPER_TYGIA', 'SCRAPER_SBV'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    
    -- Ensure unique constraint for upsert
    CONSTRAINT macro_indicators_key_date_unique UNIQUE (indicator_key, date)
);

-- Enable RLS
ALTER TABLE macro_indicators ENABLE ROW LEVEL SECURITY;

-- Allow public read
CREATE POLICY "Allow public read access" ON macro_indicators FOR SELECT USING (true);

-- Allow authenticated (or service role) update/insert
CREATE POLICY "Allow service role full access" ON macro_indicators USING (true) WITH CHECK (true);
